### ISSUE TITLE
Excessive Whitespace

### ISSUE THREAD

**Issue by netpoetica** [publicclass/express-partials#14]
It appears the EJS engine is outputting a bunch of extra whitespace inside of a tag. It's very weird:

``` javascript
<span class="editable"><% if(power){ %><%= power %><% } else{ %>(Power)<%  } %></span>
```

Outputs fine, but if you do it like this:

``` javascript
<span class="editable">
    <% if(power){ %>
        <%= power %>
     <% } else{ %>
          (Power)
      <%  } %>
</span>

```

Inside of the html span, I get something that looks like

``` javascript
<span class='editable'>"                                    
                        (Power)    

"</span>
```

**Comment by netpoetica** [comment]
Notice also the random quotation marks thrown in? Maybe this is a problem with EJS in general and not express-partials, but I've only used it with express-partials

**Comment by slaskis** [comment]
Random quotes seems like a bug to me if it does that. Is this something EJS does @visionmedia? 

But the whitespace is normal, EJS is (or at least was, last I used it) a rather simple implementation that simply buffers everything in between %> and <%. But by adding a dash before the closing ejs tag will consume the newlines, ex: `<% if(power){ -%>`

Either way it's not something express-partials does so I'll close this.
