### ISSUE TITLE
Partials require synchronous view engine?

### ISSUE THREAD

**Issue by zzen** [publicclass/express-partials#15]
I must be missing something, but before I go onto a mad coding spree to rewrite, I thought I would ask:
- as far as I can see, this library [returns partials as a value](https://github.com/publicclass/express-partials/blob/master/index.js#L286)
- express3 requires view engines to be asynchronous (ie. return rendered data in a callback)

Older engined returning rendered template synchronously (like Eco) must use [consolidate.js](https://github.com/visionmedia/consolidate.js/) to become compatible with Express3.

So while your testcases are passing, this library doesn't really work in the context of Express3, since it's using the registered view engine (hijacks res.render) and that engine should by definition be asynchronous.

Am I missing something?

**Comment by slaskis** [comment]
No, you're not missing anything. This library only really supports express 2.x styled template engines (specifically ejs) as it's goal is to bridge that particular gap.

Ideally this library would be made more generic and support all consolidate.js engines by using that unified async API but right now it doesn't.

**Comment by zzen** [comment]
Ah, I see, you need to work around that by calling `partials.register` with a reference to the sync engine. That's the part I wasn't seeing.
