### ISSUE TITLE
Call partial inside another partial

### ISSUE THREAD

**Issue by ecdeveloper** [publicclass/express-partials#22]
I'm getting an error when trying to call partial() inside another partial. 
So for example - I have a layout, where I made a call: 
<%- partial('partials/view1') %>

Inside partials/view1.ejs I have another call: 
<%- partial('partials/subview1') %>

For this second call I'm getting the error: 'partial is not defined'. 

Any hints how to fix it?

**Comment by slaskis** [comment]
Did you try this on master?

**Comment by ecdeveloper** [comment]
Yes. I've cloned the master and I still get the error. I have created a simple app to test it. Check this out - http://ecdeveloper.com/wp-content/uploads/test-partials.zip

**Comment by slaskis** [comment]
Thanks a lot for the tests!
