### ISSUE TITLE
New NPM release

### ISSUE THREAD

**Issue by rguerreiro** [publicclass/express-partials#33]
Can you give an estimate for the next npm release?

I ask this because my module express-device depends from yours and the current v0.0.6 npm release have a few bugs that were already fixed in the master branch. Because of that I use the npm feature to depend on a specific module by linking to a git repository. 

But some users are getting a lot of trouble installing my module in hosting like azure, because git isn't installed.

**Comment by shellscape** [comment]
I'd also find an npm update useful. Any traction on this?

**Comment by slaskis** [comment]
Sorry for the delay, but I've finally published version 0.1.0 with your fixes to npm.

**Comment by shellscape** [comment]
thank you
