### ISSUE TITLE
Partials fail to load with consolidate

### ISSUE THREAD

**Issue by shellscape** [publicclass/express-partials#34]
I'm using Express 3.x with express-partials (latest) and consolidate (latest) with hogan.js (latest).I can't figure out why this is happening. 

I'm getting an 500 Error: ENOENT, open error when using partials. Code to follow:
### /routes/index.js

```
exports.index = function (req, res) {
    res.render('search', { title: 'Title', layout: true, partials: { part: 'part' } });
};
```
### /app.js

```
var express = require('express'),
  routes = require('./routes'),
  http = require('http'),
  path = require('path'),
    consolidate = require('consolidate'),
    fs = require('fs'),
    partials = require('express-partials'),
    app = express();

app.use(partials());

app.configure(function () {
    app.engine('html', consolidate.hogan);
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');
  app.set('view engine', 'html');
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(express.static(path.join(__dirname, 'public')));
});

app.configure('development', function(){
  app.use(express.errorHandler());
});

app.get('/', routes.index);

http.createServer(app).listen(app.get('port'), function(){
  console.log("Express server listening on port " + app.get('port'));
});
```
### /views/layout.html

```
{{> part}}
```
### /views/part.html

```
<html>
```

Upon running the app, this is the error output I get to the page:

```
500 Error: ENOENT, open 'c:\Users\...\Search\views\﻿<html>.html'
```

As you can see, it seems to be taking the content of the partial file specified and then trying to reopen the file assuming that the content is the file name. I've found nothing to explain this on the web. What am I or express-partials doing wrong?

**Comment by slaskis** [comment]
It looks to me that consolidate [wraps hogan in an async read()](https://github.com/visionmedia/consolidate.js/blob/master/lib/consolidate.js#L134). And since express-partials only supports synchronous templates it won't work. 

I haven't used hogan nor consolidate myself but maybe if you use [`consolidate.hogan.render`](https://github.com/visionmedia/consolidate.js/blob/master/lib/consolidate.js#L440) instead, which seems  synchronous, it might work.

**Comment by slaskis** [comment]
Closing this for now.
