### ISSUE TITLE
Support modifying variables/contents of parent templates

### ISSUE THREAD

**Issue by denysonique** [publicclass/express-partials#41]
Often I would like to update the layout from a rendered view, such as the title, meta tags etc.

In RoR this is known as content_for: http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for

**Comment by slaskis** [comment]
I'm aiming to keep the implementation of this as close to the original (express 2.x) as possible.

But there's a fork that seems to implement the kind of content_for/blocks features you're looking for: 

https://github.com/RandomEtc/ejs-locals

**Comment by denysonique** [comment]
Thanks but I use HamlCoffee. I already solved this anyway by writing a simple middleware which creates req.locals for storing these vars.
