### ISSUE TITLE
App locals should be available for all views

### ISSUE THREAD

**Issue by peters** [publicclass/express-partials#8]
It would be great if the variables you define using app.locals() would be available to all
rendered / partial views. Having this ability would save us from a huge rewrite and default to the
old functionality in express < 3.0

**Comment by slaskis** [comment]
Hmm, I thought I had this [covered already](https://github.com/publicclass/express-partials/blob/master/test/test.partials.js#L113). 

Could you update that test so it fails as it does in your app? Or simply give me a failing example?

**Comment by peters** [comment]
I will provide a test case :)

**Comment by slaskis** [comment]
Appreciate it!

**Comment by peters** [comment]
Sorry about that.. mixup on my end! :)

**Comment by peters** [comment]
Though i managed to provoke a curiosity when working with relative paths and partials.

path to view that tries to render a partial: ./views/test/promo/main

<%- partial("test/promo/sub") %>

resolves to -> ./views/sub 
should be -> ./views/test/promo/sub

**Comment by slaskis** [comment]
Haha, glad we got that settled.

And you're right, totally missing tests for the partial lookup. Need to work on that, adding another issue for it though. 

Thanks!
